name: ERA5_interactive
channels:
  - conda-forge
dependencies:
  - python<3.12
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - zarr
  - dask
  - xarray
  - geoviews
  - datashader
  - matplotlib
  - panel
  - pandas
  - requests
  - pathlib
  - metpy
  - scipy
  - geopandas
  - gcsfs
  - cf_xarray
  - pip
  - pip:
      - git+https://github.com/ProjectPythia/sphinx-pythia-theme.git@theme-update
